### ISSUE TITLE
linux tools

### ISSUE THREAD

**Issue by LukaIMGGI** [fehrhart/STREAMLINEworkshop.github.io#1]
Hi, i asked about using a mac on this course and i have downloaded a virtualbox and downloaded linux and installed it. I wonder i could get some list of thing that i need to download so that i will be able to work on this course and not just follow along. 
Sincerely,
Luka

**Comment by fehrhart** [comment]
Hi Luka, all the other programs - R/RStudio, PathVisio, and Cytoscape - also work for mac. If needed you just need to check the installation instructions and select the installer for mac instead of Windows.
